### PR TITLE
Simple home page with list of active streams

### LINKED ISSUE #18: Create Home Page with Livestreams Browse
## Overview

To enhance user engagement and provide an easy way for users to discover and access live streams, we will create a homepage that features a browsing section for live streams. This page will display currently active live streams, allow users to search and filter streams, and provide quick access to stream details and viewing pages.

## Acceptance Criteria

- [x] **Homepage Design**:
    - Design a visually appealing homepage that highlights live streams.
    - Ensure the design is responsive and provides a good user experience on both desktop and mobile devices.

- [x] **Live Streams Display**:
    - Implement a section on the homepage that lists currently active live streams.
    - Display relevant information for each stream, such as the streamer's username, stream title.

- [x] **Backend Integration**:
    - Ensure the backend supports fetching and updating the list of active streams in real-time.
    - Implement necessary APIs to support search and filtering functionalities.

## References

- [ASP.NET Core Official Documentation](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-8.0)
- [Blazor Documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-8.0)
- [UX Design for Video Streaming Platforms](https://uxdesign.cc/designing-a-video-streaming-platform-ux-case-study-5c6a4b7f799)
- [Responsive Web Design](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design)

### PR DESCRIPTION
**Pull request by pietrykovsky**
**Features**:
- removed top about navbar
- redesigned home page
- added list of active streams

close #18

### CODE REVIEW

**Comment by MikolajR13** [comment]
approved

**Review by MikolajR13 — APPROVED** [review]
approved

**Review by MikolajR13 — DISMISSED** [review]
good job!!!

**Review by MikolajR13 — APPROVED** [review]
super

**Review by kuernov — APPROVED** [review]

**Pull request merged**
